# Generated by Django 6.0.7 on 2026-07-31 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_membership_is_deleted'),
        ('clients', '0002_client_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('status', models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Contacted'), (3, 'Qualified'), (4, 'Won'), (5, 'Lost')], default=1)),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='clients_lea_organiz_ec5e57_idx'), models.Index(fields=['organization', 'priority'], name='clients_lea_organiz_0c0197_idx'), models.Index(fields=['organization', 'name'], name='clients_lea_organiz_5dacae_idx'), models.Index(fields=['organization', 'email'], name='clients_lea_organiz_2c3ecf_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'email'), name='unique_lead_email_per_organization')],
            },
        ),
    ]
