# Generated by Django 6.0.7 on 2026-07-31 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_membership_is_deleted'),
        ('clients', '0004_lead_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.PositiveIntegerField(choices=[(1, 'Call'), (2, 'Email'), (3, 'Meeting'), (4, 'WhatsApp'), (5, 'Note'), (6, 'Other')], default=6)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='accounts.organization')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'interaction_type'], name='clients_int_organiz_cff98e_idx'), models.Index(fields=['organization', 'occurred_at'], name='clients_int_organiz_239bfd_idx'), models.Index(fields=['organization', 'client'], name='clients_int_organiz_4098f8_idx'), models.Index(fields=['organization', 'lead'], name='clients_int_organiz_1c599c_idx')],
            },
        ),
    ]
