# Generated by Django 6.0.7 on 2026-07-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
