USERS_RETRIEVED_SUCCESSFULLY = "Users retrieved successfully."
USER_RETRIEVED_SUCCESSFULLY = "User retrieved successfully."
USERS_RETRIEVAL_FAILED = "Failed to retrieve users."
USER_RETRIEVAL_FAILED = "Failed to retrieve user."
USERS_CREATED_SUCCESSFULLY = "User created successfully."
USER_CREATION_FAILED = "Failed to create users."
USER_UPDATION_FAILED = "Failed to update users."
USER_DELETION_FAILED = "Failed to delete users."
USER_UPDATED_SUCCESSFULLY = "User updated successfully."
USER_DELETED_SUCCESSFULLY = "User deleted successfully."

ORGANIZATIONS_RETRIEVED_SUCCESSFULLY = "Organizations retrieved successfully."
ORGANIZATION_RETRIEVED_SUCCESSFULLY = "Organization retrieved successfully."
ORGANIZATIONS_RETRIEVAL_FAILED = "Failed to retrieve organizations."
ORGANIZATION_RETRIEVAL_FAILED = "Failed to retrieve organization."
ORGANIZATIONS_CREATED_SUCCESSFULLY = "Organizations created successfully."
ORGANIZATIONS_CREATION_FAILED = "Failed to create organizations."
ORGANIZATIONS_UPDATION_FAILED = "Failed to update organizations."
ORGANIZATIONS_DELETION_FAILED = "Failed to delete organizations."
ORGANIZATION_UPDATED_SUCCESSFULLY = "Organization updated successfully."
ORGANIZATION_DELETED_SUCCESSFULLY = "Organization deleted successfully."

MEMBERSHIPS_RETRIEVED_SUCCESSFULLY = "Memberships retrieved successfully."
MEMBERSHIP_RETRIEVED_SUCCESSFULLY = "Membership retrieved successfully."
MEMBERSHIPS_RETRIEVAL_FAILED = "Failed to retrieve memberships."
MEMBERSHIP_RETRIEVAL_FAILED = "Failed to retrieve membership."
MEMBERSHIPS_CREATED_SUCCESSFULLY = "Memberships created successfully."
MEMBERSHIPS_CREATION_FAILED = "Failed to create memberships."
MEMBERSHIPS_UPDATION_FAILED = "Failed to update memberships."
MEMBERSHIPS_DELETION_FAILED = "Failed to delete memberships."
MEMBERSHIPS_UPDATED_SUCCESSFULLY = "Membership updated successfully."
MEMBERSHIPS_DELETED_SUCCESSFULLY = "Membership deleted successfully."
SELECTED_USER_INACTIVE = "Selected user is inactive."
SELECTED_USER_DELETED = "Selected user is deleted."
SELECTED_ORGANIZATION_INACTIVE = "Selected organization is inactive."
SELECTED_ORGANIZATION_DELETED = "Selected organization is deleted."

CLIENT_NAME_CANNOT_EMPTY="Client name cannot be empty."
CLIENT_EMAIL_EXISTS_IN_ORANZATION="A client with this email already exists in this organization."
CLIENTS_RETRIVED_SUCCESSFULLY="Clients retrieved successfully."
CLIENT_RETRIVED_SUCCESSFULLY="Client retrieved successfully."
CLIENTS_RETRIEVAL_FAILED = "Failed to retrieve clients."
CLIENT_RETRIEVAL_FAILED = "Failed to retrieve client."
CLIENT_CREATION_FAILED = "Failed to create client."
CLIENT_UPDATION_FAILED = "Failed to create client."
CLIENT_DELETION_FAILED = "Failed to delete client."
CLIENT_CREATED_SUCCESSFULLY = "Client created successfully."
CLIENT_UPDATED_SUCCESSFULLY = "Client updated successfully."
CLIENT_DELETED_SUCCESSFULLY = "Client deleted successfully."


VALIDATION_FAILURE = "Validation failed."