# Login
INVALID_CREDENTIALS = "Invalid email or password."
LOGIN_SUCCESS = "Login successfull."
LOGIN_FAILURE = "Login failed."

PASSWORD_MISMATCH = "Password do not match."
ORGANIZATION_NOT_EXISTS = "Organization does not exist, is inactive or has been deleted."
SUPERUSER_CANNOT_CREATE = "Superuser can only create users with ADMIN role."
NO_PERMISSION = "You do not have permission to add users to this organization."
USERS_RETRIEVED_SUCCESSFULLY = "Users fetched successfully."
USERS_RETRIEVAL_FAILED = "Failed to retrieve users."
USER_CREATED_SUCCESSFULLY = "User created successfully."
USER_CREATION_FAILED = "Failed to create users."
USER_RETRIEVED_SUCCESSFULLY = "User data fetched successfully."
USER_RETRIEVAL_FAILED = "Failed to fetch user."
USER_UPDATION_FAILED = "Failed to update users."
USER_DELETION_FAILED = "Failed to delete users."
USER_UPDATED_SUCCESSFULLY = "User updated successfully."
USER_DELETED_SUCCESSFULLY = "User deleted successfully."

ORGANIZATIONS_RETRIEVED_SUCCESSFULLY = "Organizations retrieved successfully."
ORGANIZATION_RETRIEVED_SUCCESSFULLY = "Organization retrieved successfully."
ORGANIZATIONS_RETRIEVAL_FAILED = "Failed to retrieve organizations."
ORGANIZATION_RETRIEVAL_FAILED = "Failed to retrieve organization."
ORGANIZATIONS_CREATED_SUCCESSFULLY = "Organizations created successfully."
ORGANIZATIONS_CREATION_FAILED = "Failed to create organizations."
ORGANIZATIONS_UPDATION_FAILED = "Failed to update organizations."
ORGANIZATIONS_DELETION_FAILED = "Failed to delete organizations."
ORGANIZATION_UPDATED_SUCCESSFULLY = "Organization updated successfully."
ORGANIZATION_DELETED_SUCCESSFULLY = "Organization deleted successfully."

MEMBERSHIPS_RETRIEVED_SUCCESSFULLY = "Memberships retrieved successfully."
MEMBERSHIP_RETRIEVED_SUCCESSFULLY = "Membership retrieved successfully."
MEMBERSHIPS_RETRIEVAL_FAILED = "Failed to retrieve memberships."
MEMBERSHIP_RETRIEVAL_FAILED = "Failed to retrieve membership."
MEMBERSHIPS_CREATED_SUCCESSFULLY = "Memberships created successfully."
MEMBERSHIPS_CREATION_FAILED = "Failed to create memberships."
MEMBERSHIPS_UPDATION_FAILED = "Failed to update memberships."
MEMBERSHIPS_DELETION_FAILED = "Failed to delete memberships."
MEMBERSHIPS_UPDATED_SUCCESSFULLY = "Membership updated successfully."
MEMBERSHIPS_DELETED_SUCCESSFULLY = "Membership deleted successfully."
SELECTED_USER_INACTIVE = "Selected user is inactive."
SELECTED_USER_DELETED = "Selected user is deleted."
SELECTED_ORGANIZATION_INACTIVE = "Selected organization is inactive."
SELECTED_ORGANIZATION_DELETED = "Selected organization is deleted."

CLIENT_NAME_CANNOT_EMPTY="Client name cannot be empty."
CLIENT_EMAIL_EXISTS_IN_ORANZATION="A client with this email already exists in this organization."
CLIENTS_RETRIVED_SUCCESSFULLY="Clients retrieved successfully."
CLIENT_RETRIVED_SUCCESSFULLY="Client retrieved successfully."
CLIENTS_RETRIEVAL_FAILED = "Failed to retrieve clients."
CLIENT_RETRIEVAL_FAILED = "Failed to retrieve client."
CLIENT_CREATION_FAILED = "Failed to create client."
CLIENT_UPDATION_FAILED = "Failed to create client."
CLIENT_DELETION_FAILED = "Failed to delete client."
CLIENT_CREATED_SUCCESSFULLY = "Client created successfully."
CLIENT_UPDATED_SUCCESSFULLY = "Client updated successfully."
CLIENT_DELETED_SUCCESSFULLY = "Client deleted successfully."

LEAD_NAME_CANNOT_EMPTY = "Lead name cannot be empty."
LEAD_EMAIL_EXISTS_IN_ORGANIZATION = "A lead with this email already exists in this organization."
LEADS_RETRIVED_SUCCESSFULLY="Leads retrieved successfully."
LEAD_RETRIVED_SUCCESSFULLY="Lead retrieved successfully."
LEADS_RETRIEVAL_FAILED = "Failed to retrieve leads."
LEAD_RETRIEVAL_FAILED = "Failed to retrieve lead."
LEAD_CREATION_FAILED = "Failed to create lead."
LEAD_UPDATION_FAILED = "Failed to update lead."
LEAD_DELETION_FAILED = "Failed to delete lead."
LEAD_CREATED_SUCCESSFULLY = "Lead created successfully."
LEAD_UPDATED_SUCCESSFULLY ="Lead updated successfully."
LEAD_DELETED_SUCCESSFULLY = "Lead deleted successfully."

INTERACTION_EITHER_CLIENT_OR_LEAD = "Interaction must be linked to either a client or a lead."
INTERACTION_CANNOT_BE_LINKED = "Interaction cannot be linked to both client and lead at the same time."
INTERACTIONS_RETRIVED_SUCCESSFULLY = "Interactions retrieved successfully."
INTERACTIONS_RETRIEVAL_FAILED = "Failed to retrieve Interactions."
INTERACTION_CREATION_FAILED = "Failed to create Interaction."
INTERACTION_UPDATION_FAILED = "Failed to update Interaction."
INTERACTION_DELETION_FAILED = "Failed to delete Interaction."
INTERACTION_CREATED_SUCCESSFULLY = "Interaction created successfully."
INTERACTION_UPDATED_SUCCESSFULLY = "Interaction updated successfully."
INTERACTION_DELETED_SUCCESSFULLY = "Interaction deleted successfully."

TASK_EITHER_CLIENT_OR_LEAD = "A task must be linked to either a client or a lead."
TASK_CANNOT_BE_LINKED = "A task cannot be linked to both a client and a lead at the same time."
COMPLETED_AT_REQUIRED = "completed_at is required when status is completed."
STATUS_MUST_COMPLETED = "status must be completed when completed_at is set."
IS_COMPLETED_TRUE = "status must be completed when is_completed is true."
ASSIGNED_TO_ORGANIZATION = "assigned_to must belong to the same organization."
TASKS_LISTS_RETRIEVED_SUCCESSFULLY = "Task lists retrieved successfully."
TASKS_RETRIEVED_SUCCESSFULLY = "Tasks retrieved successfully."
TASKS_LISTS_RETRIEVAL_FAILED = "Failed to retrieve tasks lists."
TASKS_RETRIEVAL_FAILED = "Failed to retrieve tasks."
TASKS_CREATION_FAILED = "Failed to create tasks."
TASKS_UPDATION_FAILED = "Failed to update tasks."
TASKS_DELETION_FAILED = "Failed to delete tasks."
TASKS_CREATED_SUCCESSFULLY = "Tasks created successfully."
TASKS_UPDATED_SUCCESSFULLY = "Tasks updated successfully."
TASKS_DELETED_SUCCESSFULLY = "Tasks deleted successfully."

NOTE_EITHER_CLIENT_OR_LEAD = "A note must be linked to either a client or a lead."
NOTE_CANNOT_BE_LINKED = "A note cannot be linked to both a client and a lead at the same time."
NOTES_RETRIEVED_SUCCESSFULLY = "Notes retrieved successfully."
NOTES_RETRIEVAL_FAILED = "Failed to retrieve notes."
NOTE_RETRIEVAL_FAILED = "Failed to retrieve note."
NOTE_CREATION_FAILED = "Failed to create note."
NOTE_UPDATION_FAILED = "Failed to update note."
NOTE_DELETION_FAILED = "Failed to delete note."
NOTE_RETRIEVED_SUCCESSFULLY = "Note retrieved successfully."
NOTE_CREATED_SUCCESSFULLY = "Note created successfully."
NOTE_UPDATED_SUCCESSFULLY = "Note updated successfully."
NOTE_DELETED_SUCCESSFULLY = "Note deleted successfully."

USER_NOT_IN_ORGANIZATION = "User does not belong to any organization."
CANNOT_ATTACH_LOG = "You cannot attach this log to another organization’s run."

ACTIVITY_SUMMARY_RETRIEVED_SUCCESSFULLY= "Activity Summary retrived successfully."
ACTIVITY_SUMMARY_RETRIEVAL_FAILED= "Activity Summary retrival failed."
OVERDUE_TASKS_RETRIEVED_SUCCESSFULLY = "Overdue task retrieved successfully."
OVERDUE_TASKS_RETRIEVAL_FAILED = "Overdule task retrival failed."
TIMELINE_RETRIEVED_SUCCESSFULLY = "Timeline retrieved successfully."
TIMELINE_RETRIEVAL_FAILED = "Timeline retrieval failed."
CLIENT_TIMELINE_RETRIEVED_SUCCESSFULLY= "Client timeline retrieved successfully."
CLIENT_TIMELINE_RETRIEVAL_FAILED= "Client timeline retrival failed."
LEAD_SUMMARY_RETRIEVED_SUCCESSFULLY= "Lead summary retrieved successfully."
LEAD_SUMMARY_RETRIEVAL_FAILED= "Lead summary retrival failed."
CLIENT_ATTENTION_RETRIEVED_SUCCESSFULLY= "Clients needing attention retrieved successfully."
CLIENT_ATTENTION_RETRIEVAL_FAILED= "Clients needing attention retrival failed."
DAILY_SUMMARY_RETRIEVED_SUCCESSFULL= "Daily summary retrieved successfully."
DAILY_SUMMARY_RETRIEVAL_FAILED= "Daily summary retrival failed."
LEAD_PRIORITY_RETRIEVED_SUCCESSFULL= "Lead prioritization retrieved successfully."
LEAD_PRIORITY_RETRIEVAL_FAILED= "Lead prioritization retrival failed."
FOLLOW_UP_RETRIEVED_SUCCESSFULL= "Follow-up suggestions retrieved successfully."
FOLLOW_UP_RETRIEVAL_FAILED= "Follow-up suggestions retrival failed."
NATURAL_LANGUAGE_PROCESSED_SUCCESSFULL= "Natural language query processed successfully."
NATURAL_LANGUAGE_PROCESSED_UNSUCCESSFULL= "Natural language query processed unsuccessfull."

REGISTER_SUCCESSFULL = "Registration successfull."
REGISTER_FAILED = "Registration failed."

VALIDATION_FAILURE = "Validation failed."

