USERS_RETRIEVED_SUCCESSFULLY = "Users retrieved successfully."
USER_RETRIEVED_SUCCESSFULLY = "User retrieved successfully."
USERS_RETRIEVAL_FAILED = "Failed to retrieve users."
USER_RETRIEVAL_FAILED = "Failed to retrieve user."
USERS_CREATED_SUCCESSFULLY = "User created successfully."
USER_CREATION_FAILED = "Failed to create users."
USER_UPDATION_FAILED = "Failed to update users."
USER_DELETION_FAILED = "Failed to delete users."
USER_UPDATED_SUCCESSFULLY = "User updated successfully."
USER_DELETED_SUCCESSFULLY = "User deleted successfully."

ORGANIZATIONS_RETRIEVED_SUCCESSFULLY = "Organizations retrieved successfully."
ORGANIZATION_RETRIEVED_SUCCESSFULLY = "Organization retrieved successfully."
ORGANIZATIONS_RETRIEVAL_FAILED = "Failed to retrieve organizations."
ORGANIZATION_RETRIEVAL_FAILED = "Failed to retrieve organization."
ORGANIZATIONS_CREATED_SUCCESSFULLY = "Organizations created successfully."
ORGANIZATIONS_CREATION_FAILED = "Failed to create organizations."
ORGANIZATIONS_UPDATION_FAILED = "Failed to update organizations."
ORGANIZATIONS_DELETION_FAILED = "Failed to delete organizations."
ORGANIZATION_UPDATED_SUCCESSFULLY = "Organization updated successfully."
ORGANIZATION_DELETED_SUCCESSFULLY = "User deleted successfully."



VALIDATION_FAILURE = "Validation failed."