# Generated by Django 6.0.7 on 2026-07-31 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_membership_is_deleted'),
        ('clients', '0005_interaction'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='clients.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='tasks_note_organiz_946712_idx'), models.Index(fields=['client', 'created_at'], name='tasks_note_client__26de01_idx'), models.Index(fields=['lead', 'created_at'], name='tasks_note_lead_id_0ffed5_idx')],
            },
        ),
    ]
