# Generated by Django 6.0.7 on 2026-08-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_note_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Completed'), (4, 'Cancelled')], default=1),
        ),
    ]
