# Generated by Django 6.0.7 on 2026-07-31 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_membership_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('status', models.TextField(choices=[(1, 'Pending'), (2, 'Running'), (3, 'Completed'), (4, 'Failed'), (5, 'Cancelled')], default=1)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_runs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentActionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.PositiveIntegerField(choices=[(1, 'Tool Call'), (2, 'Tool Result'), (3, 'Prompt'), (4, 'Decision'), (5, 'Error')], db_index=True)),
                ('tool_name', models.CharField(blank=True, max_length=120)),
                ('action_name', models.CharField(blank=True, max_length=120)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('step_number', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_action_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_action_logs', to='accounts.organization')),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='agentic.agentrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['organization', 'status'], name='agentic_age_organiz_e5dfad_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['organization', 'created_at'], name='agentic_age_organiz_ca112f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent_name'], name='agentic_age_agent_n_bffae0_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.CheckConstraint(condition=models.Q(('agent_name', ''), _negated=True), name='agentrun_agent_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='agentactionlog',
            index=models.Index(fields=['organization', 'agent_run'], name='agentic_age_organiz_0de5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionlog',
            index=models.Index(fields=['agent_run', 'created_at'], name='agentic_age_agent_r_f8c1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionlog',
            index=models.Index(fields=['action_type', 'created_at'], name='agentic_age_action__fc77d1_idx'),
        ),
    ]
